Feature/list
wecode-bootcamp-korea/9-rush-hour-backend pull request #5
Opened 2020-06-29 07:48 UTC by monsterkos

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
 - 상품 카테고리별 리스트 뷰 구현 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
 - 전체 / 배쓰 밤 / 버블 바 각각의 상품 리스트 별 엔드포인트 구현

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-06-29 08:00 UTC, devops-andrew requested changes

2020-06-29 08:00 UTC, devops-andrew commented on lush/settings.py
> +ALLOWED_HOSTS = ["*","10.58.1.180","10.58.1.180:8000"]
공개주소는 아니지만 이런식으로 아이피가 노출되는건 좋지 않습니다. 외부설정 파일에 등록해서 적용해주세요.

2020-06-29 08:00 UTC, devops-andrew commented on lush/settings.py
> +LOGGING = {
실 운영서버의 코드에 로깅을 담지마세요.

2020-06-29 08:00 UTC, devops-andrew commented on product/views.py
> +class ListView(View):
무엇에 대한 리스트 뷰인가요? 클래스명이 너무 포괄적입니다.

2020-06-29 08:00 UTC, devops-andrew commented on product/urls.py
> +        path("goods_list", ListView.as_view())
아래 뷰클래스에서 말씀드리겠습니다.

2020-06-29 08:00 UTC, devops-andrew commented on product/views.py
> +
임포트 순서는 

파이썬 라이브러리

장고 모듈

사용자 클래스
순으로 정렬해주세요.

2020-06-29 08:00 UTC, devops-andrew commented on product/views.py
> +        list_count = 28
list_count는 고정값인가요? 그렇다면 상수처리해서 메소드밖으로 빼서 참조하는게 좋습니다.

LIST_COUNT = 28

2020-06-29 08:00 UTC, devops-andrew commented on product/views.py
> +        total_ctgry = rename_list.values(
```suggestion
        total_category = rename_list.values(
```

변수명 줄여쓰는 습관은 지양해주세요. 올바른 변수명 작성하는 습관을 지향해주세요.

2020-06-29 08:00 UTC, devops-andrew commented on product/views.py
> +        category_code = request.GET.get("cateCd")
```suggestion
        category_code = request.GET.get("category_code")
```
참고하는 대상에서 그런 코드명을 썼다고 나도 그렇게 해야할 필요는 없습니다. 정확한 변수명 사용을 해주세요.

2020-06-29 08:00 UTC, devops-andrew commented on product/views.py
> +        total_sub_ctgry = rename_sub_list.values(
```suggestion
        total_sub_category = rename_sub_list.values(
```

2020-06-29 08:00 UTC, devops-andrew commented on product/views.py
> +                product_info["sub_ctgry_name"] = product.sub_category.name
마찬가지로 수정해주세요.

2020-06-29 08:00 UTC, ulfrid commented on product/views.py
> +                product_info["sub_ctgry_code"] = product.sub_category.code
여기도 수정해주세요.

2020-06-29 08:00 UTC, ulfrid commented on product/views.py
> +            else :
else제거하고 아래코드들 한탭 당겨주세요.

2020-06-30 05:37 UTC, soheon-lee commented
컨플릭트 해결해.주.시.라.고.요.  🧐

2020-06-30 05:51 UTC, soheon-lee commented on product/views.py
> +from .models                        import Product, Category, SubCategory
서로 다른 클래스 import 할 때에는 행으로 분리해주세요

2020-06-30 05:51 UTC, soheon-lee commented on product/views.py
> +        all_products = Product.objects.all().prefetch_related(
`=` 기준으로 코드 정렬해주세요

2020-06-30 05:53 UTC, soheon-lee commented on user/urls.py
>  from .views import LoginView, SignUp
중복 확인해주세요

2020-06-30 06:04 UTC, devops-andrew requested changes

2020-06-30 06:04 UTC, ulfrid commented on product/views.py
> +        except:
무엇에 대한 익셉션일까요? 이런식의 처리는 에러처리에 도움 되지 않습니다
에러나면 무조건 400 리턴 할 테니까요.

2020-06-30 06:15 UTC, monsterkos commented on product/views.py
> +        except:
try / except 가 필요없는 것 같아서 제거하겠습니다

2020-06-30 06:29 UTC, merged