제품별 상세페이지 엔드포인트 구현
wecode-bootcamp-korea/9-rush-hour-backend pull request #7
Opened 2020-06-30 01:55 UTC by monsterkos

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       

 - 각 제품별 상품코드를 기준으로 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)

 - 상세 설명에 대한 기본적인 데이터와 html 코드 통신 목적
 - <slug:product_id> 로 각 제품의 코드별로 엔드포인트 구분

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-06-30 01:56 UTC, evergreen-david requested changes

2020-06-30 01:56 UTC, evergreen-david commented on product/urls.py
> +        ]
```suggestion
]
```

2020-06-30 01:56 UTC, evergreen-david commented on product/urls.py
> +        path("/<slug:product_id>", ProductDetailView.as_view()),
```suggestion
    path("/goods_list", ProductListView.as_view()),
    path("/<slug:product_id>", ProductDetailView.as_view()),
```

2020-06-30 02:04 UTC, evergreen-david requested changes

2020-06-30 02:04 UTC, evergreen-david commented on product/views.py
> +            return product_list
리스트 컴프리헨션으로 바꿔 보세요~!

2020-06-30 02:06 UTC, evergreen-david requested changes

2020-06-30 02:06 UTC, evergreen-david commented on product/views.py
> +                    )
73-79 라인과 중복코드 확인 부탁 드립니다.

2020-06-30 02:29 UTC, evergreen-david requested changes

2020-06-30 02:29 UTC, evergreen-david commented on product/views.py
> +                                    )
줄바꿈 시마다 들여쓰기가 되어있는데 줄바꾸면 기본적으로 4칸만 들여쓰기 해야합니다. 정렬 부탁 드려요.

2020-06-30 02:29 UTC, evergreen-david commented on product/views.py
> +                )
여기도 정리 부탁 드립니다.

2020-06-30 02:29 UTC, evergreen-david commented on product/views.py
> +        detail_info["product_name"] = product_detail[0].name
우선 filter 결과가 두개이상인가요 ? 그리고 두개이상이라면 product_detail[0] 보다는 -> product_detail.first() 이런식으로 사용하는 편이 좋을 것 같습니다.

2020-06-30 02:31 UTC, evergreen-david requested changes

2020-06-30 02:31 UTC, evergreen-david commented on product/views.py
> +                        )
rename_list 변수로 따로 저장하지 않아도 연속적으로 .values 로 호출할 수 있지않나요 ?

2020-06-30 02:31 UTC, evergreen-david commented on product/views.py
> +                        )
) align 부탁드립니다.

2020-06-30 02:31 UTC, evergreen-david commented on product/views.py
> +                )
) align 부탁드립니다.

2020-06-30 02:31 UTC, evergreen-david commented on product/views.py
> +                        )[offset:limit]
괄호 align 부탁 드립니다.

2020-06-30 02:33 UTC, evergreen-david requested changes

2020-06-30 02:33 UTC, evergreen-david commented on product/views.py
> +        def send_info(lists):
send_info 함수 get 함수안에 들어있는데 클래스 밖으로 정리하는게 좋을 것 같습니다. get 함수길이가 길어지므로 가독성에 좋지않은것같아요! 함수 이름도 send_info 인데 make_product_list 와 같은 식으로 바꿔주는게좋을것같아요.

2020-06-30 02:36 UTC, evergreen-david requested changes

2020-06-30 02:36 UTC, evergreen-david commented on product/urls.py
> +        path("/goods_list", ProductListView.as_view()),
goods 라고만 해도 될것같습니다. 그리고 list 써도 될것같은데 쓰더라도 언더스코어보다는 엔드포인트 주소는 - 로 구분해주세요.
```suggestion
        path("/goods", ProductListView.as_view()),
```

2020-06-30 06:36 UTC, devops-andrew requested changes

2020-06-30 06:36 UTC, ulfrid commented on product/views.py
> +        ).first()
수정해도 무방한 상황이라면~!
```
 product_detail = Product.objects.filter(
            product_number=product_id
        ).prefetch_related(
            "thumbnail_image",
            "weight".
            "related_products"
        ).select_related(
            "detail"
        ).first()
```

2020-06-30 06:36 UTC, ulfrid commented
컨플릭트 수정해주세요.

2020-07-01 07:49 UTC, soheon-lee commented on product/views.py
> +                all_products = Product.objects.all().prefetch_related(
뒤에 `filter()`메소드가 있기 때문에 `all()`메소드는 사용하지 않으셔도 됩니다. 지워주세용.

2020-07-01 07:51 UTC, soheon-lee commented on product/views.py
> +                detail_info = {}
밑에서 detail_info 딕셔너리를 정의하므로, 사용되지 않는 딕셔너리 입니다. 제거해주세요.

2020-07-01 07:56 UTC, soheon-lee commented on product/views.py
> +                detail_info["related"]      = make_product_list(related_products)
related_products_id를 만드는 부분과 related_products 만드는 부분을 합칠 수 있습니다. (2중 list comprehension)으로.
하나로 만드셔서 detail_info의 'related'키도 102번째 줄부터 시작되는 detail_info 딕셔너리 내부에 함께 넣어주세요.

2020-07-01 07:56 UTC, soheon-lee commented on product/views.py
> +                    "html"          :product_detail.detail.html,
```suggestion
                    "product_name"  : product_detail.name,
                    "hash_tag"      : product_detail.hash_tag,
                    "image"         : product_detail.thumbnail_image.first().url,
                    "price"         : int(product_detail.price),
                    "weight"        : product_detail.weight.first().weight_g,
                    "extra_price"   : int(product_detail.weight.first().extra_price),
                    "video"         : product_detail.detail.video_url,
                    "html"          : product_detail.detail.html,
```
콜론 뒤에 한 줄 띄워주세요 😄

2020-07-01 11:25 UTC, soheon-lee commented on product/views.py
> +                filters = {"sub_category__code":sub_category_code}
```suggestion
            if sub_category_code:
                filters = {"sub_category__code":sub_category_code}
                
            if category_code:
                filters = {"sub_category__category__code":category_code}
```

2020-07-01 11:35 UTC, soheon-lee commented on product/views.py
> +                ]
객체의 id 를 꺼내오고 다시 그 id마다 객체를 찾아오지 않아도 될 것 같습니다.

2020-07-01 11:36 UTC, soheon-lee commented on product/urls.py
> +    path("/goods-list", ProductListView.as_view()),
혹싀 RESTful url이 탐나시진 않으시나요? ㅎ.ㅎ

2020-07-01 12:05 UTC, soheon-lee commented
LGTM

2020-07-01 12:19 UTC, merged