Feature/order 배송지 관리 구현
wecode-bootcamp-korea/9-rush-hour-backend pull request #8
Opened 2020-06-30 10:54 UTC by yoonbitnara

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 배송지 관리 구현
         
		 
## 수정 사항들 자세한 내용
- 배송지 추가 , 수정 , 삭제 구현.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-01 08:17 UTC, devops-andrew requested changes

2020-07-01 08:17 UTC, ulfrid commented on order/views.py
> +        data            = json.loads(request.body)
delete method는 GET과 마찬가지로 body로 받지 않습니다.

2020-07-01 08:17 UTC, ulfrid commented on order/views.py
> +    def put(self,request):
put을 해야하는 대상이면 url에경로에서 특정되는 id값을 주세요. body를 통하지 말고, url parameter로 처리해주세요. 위의 delete도 마찬가지 입니다.

2020-07-01 12:23 UTC, evergreen-david requested changes

2020-07-01 12:23 UTC, evergreen-david commented on order/views.py
> +from .models        import *
필요한 모델만 임포트하도록 수정해주세요.

2020-07-01 12:23 UTC, evergreen-david commented on order/views.py
> +            return JsonResponse({'message': 'Invalid key.'.e}, status = 401)
키에러면 일반적으로 400에러로 처리하면 될것같습니다.

2020-07-01 12:23 UTC, evergreen-david commented on order/views.py
> +            return JsonResponse({'message': 'Invalid key.'.e}, status = 401)
all_sport

2020-07-01 12:23 UTC, evergreen-david commented on order/views.py
> +            return JsonResponse({'message':'SUCCESS POST'}, status=200)
success 의미는 200에 포함되어 있으므로 status 코드만 리턴해도 됩니다.
```suggestion
            return HttpResponse(status=200)
```

2020-07-01 12:23 UTC, evergreen-david commented on order/views.py
> +                    ).save()
```suggestion
                ).save()
```

2020-07-01 12:23 UTC, evergreen-david commented on order/urls.py
> +        path('/shipping', ShippingManagementView.as_view())
8칸띄워진것같은데 들여쓰기는 기본적으로 4칸입니다. 수정 부탁 드립니다.

2020-07-01 12:26 UTC, yoonbitnara commented on order/views.py
> +            return JsonResponse({'message': 'Invalid key.'.e}, status = 401)
all_sport가 뭐죠 ..?

2020-07-02 17:11 UTC, soheon-lee commented on order/views.py
> +                    ).save()
```suggestion
            Shipping(
                        user_id         = data['user_id'],
                        name            = data['name'],
                        recipient       = data['recipient'],
                        address         = data['address'],
                        phone_number    = data['phone_number']
                    ).save()
```

2020-07-02 17:11 UTC, soheon-lee commented on order/views.py
> +            return JsonResponse({'message': 'Invalid key.'}, status = 401)
```suggestion
            return JsonResponse({'message': 'INVALID_KEY'}, status = 401)
```

2020-07-02 17:12 UTC, soheon-lee commented on order/views.py
> +        return JsonResponse({'comments':list(shipping_list)}, status=200)
배송지 조회시 특정 사용자의 배송지만 골라서 조회하는 경우가 대다수입니다. user 정보를 query string으로 받거나, login_decorator에서 꺼내와주세요.

2020-07-02 17:13 UTC, soheon-lee commented on order/views.py
> +        return JsonResponse({'comments':list(shipping_list)}, status=200)
`comments` 라는 키는 배송지 정보에 대한 이름으로 적절하지 않을 것 같습니다. 보다 명확한 이름으로 변경해주세요

2020-07-02 17:14 UTC, soheon-lee commented on order/views.py
> +            return JsonResponse({'message': 'Invalid key.'}, status = 400)
```suggestion
            return JsonResponse({'message': 'INVALID_KEY'}, status = 400)
```

2020-07-02 17:15 UTC, soheon-lee commented on order/views.py
> +            return JsonResponse({'message':'SUCCESS UPDATE'}, status=200)
위에 있는 `delete` 메소드의 성공 경우에 나타내는 메세지와 스타일을 통일 해주세요
```suggestion
            return JsonResponse({'message':'UPDATE_SUCCESS'}, status=200)
```

2020-07-02 17:15 UTC, soheon-lee commented on order/views.py
> +        return JsonResponse({'message':'DELETE SUCCESS'}, status=200)
```suggestion
        return JsonResponse({'message':'DELETE_SUCCESS'}, status=200)
```

2020-07-03 04:58 UTC, soheon-lee commented on order/views.py
> +        user_id       = data['user']
유저 정보는 body에 담아서 보내지 않습니다. 토큰에서 꺼내와주세요

2020-07-03 05:03 UTC, soheon-lee commented
LGTM

2020-07-03 05:03 UTC, merged